changelog:
  categories:
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: CI/CD
      labels:
        - ci
        - build
        - chore
    - title: Other Changes
      labels:
        - "*"
